apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongo-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "mongodb-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: user
            objectAlias: user
          - path: password
            objectAlias: password
          - path: database
            objectAlias: database
          - path: host
            objectAlias: host
          - path: port
            objectAlias: port
  secretObjects:
    - secretName: mongo-secret
      type: Opaque
      data:
        - objectName: user
          key: username
        - objectName: password
          key: password
        - objectName: database
          key: database
        - objectName: host
          key: host
        - objectName: port
          key: port
