apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
  labels:
    app: mongo
spec:
  serviceAccountName: secret-store-sa # Must match the service account created for secret store CSI
  containers:
  - name: mongo-container
    image: mongo:latest
    ports:
    - containerPort: 27017
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: username
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: password
    - name: MONGO_INITDB_DATABASE
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: database
    volumeMounts:
    - name: mongo-secrets-store
      mountPath: "/mnt/secrets-store"
      readOnly: true
    - name: mongo-data
      mountPath: /bitnami/mongo
  volumes:
  - name: mongo-secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "mongo-secrets"  # Must match with the name of the SecretProviderClass
  - name: mongo-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-database
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
---