apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongo-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "mongodb-credentials"
        objectType: "secretsmanager"
  secretObjects:  # This section defines the Kubernetes secret that will be created
    - secretName: mongo-secret
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: database
          key: database
        - objectName: host
          key: host
        - objectName: port
          key: port
