prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchNames:
      - default
      - argocd
      - nginx-ingress
    serviceMonitorSelector:
      matchLabels:
        release: prometheus
grafana:
  enabled: false