apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  name: throttler-server
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: throttler
  port: http
---
apiVersion: policy.linkerd.io/v1beta1
kind: HTTPRoute
metadata:
  name: throttler-metric-route
  namespace: default
spec:
  parentRefs:
  - name: throttler-server
    kind: Server
    group: policy.linkerd.io
  rules:
  - matches:
    - path:
        value: "/metrics"
        type: "Exact"
      method: GET
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: throttler-metric-policy
  namespace: default
spec:
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: throttler-metric-route
  requiredAuthenticationRefs:
  - name: throttler-metric-authn
    kind: MeshTLSAuthentication
    group: policy.linkerd.io
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: throttler-metric-authn
  namespace: default
spec:
  identities:
  - "prometheus-kube-prometheus-prometheus.monitoring.serviceaccount.identity.linkerd.cluster.local"
---
apiVersion: policy.linkerd.io/v1beta1
kind: HTTPRoute
metadata:
  name: throttler-probe-route
  namespace: default
spec:
  parentRefs:
  - name: throttler-server
    kind: Server
    group: policy.linkerd.io
  rules:
    - matches:
      - path:
          value: "/v1/healthcheck"
          type: "Exact"
        method: GET
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: throttler-probe-policy
  namespace: default
spec:
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: throttler-probe-route
  requiredAuthenticationRefs:
  - name: throttler-probe-authn
    kind: NetworkAuthentication
    group: policy.linkerd.io
---
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  name: throttler-probe-authn
  namespace: default
spec:
  networks:
  - cidr: 0.0.0.0/0
  - cidr: ::/0