apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    linkerd.io/control-plane-ns: linkerd
  name: linkerd-controller
  namespace: linkerd
spec:
  namespaceSelector:
    matchNames:
    - linkerd
    - linkerd-viz
    - linkerd-jaeger
  podMetricsEndpoints:
  - interval: 10s
    relabelings:
    - action: keep
      regex: admin-http
      sourceLabels:
      - __meta_kubernetes_pod_container_port_name
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_container_name
      targetLabel: component
    scrapeTimeout: 10s
  selector:
    matchLabels: {}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    linkerd.io/control-plane-ns: linkerd
  name: linkerd-proxy
  namespace: linkerd
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - interval: 10s
    relabelings:
    - action: keep
      regex: ^linkerd-proxy;linkerd-admin;linkerd$
      sourceLabels:
      - __meta_kubernetes_pod_container_name
      - __meta_kubernetes_pod_container_port_name
      - __meta_kubernetes_pod_label_linkerd_io_control_plane_ns
    - action: replace
      sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: namespace
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: pod
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_linkerd_io_proxy_job
      targetLabel: k8s_job
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_linkerd_io_proxy_job
    - action: labelmap
      regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
    - action: labelmap
      regex: __meta_kubernetes_pod_label_linkerd_io_(.+)
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
      replacement: __tmp_pod_label_$1
    - action: labelmap
      regex: __tmp_pod_label_linkerd_io_(.+)
      replacement: __tmp_pod_label_$1
    - action: labeldrop
      regex: __tmp_pod_label_linkerd_io_(.+)
    - action: labelmap
      regex: __tmp_pod_label_(.+)
    scrapeTimeout: 10s
  selector:
    matchLabels: {}