apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notifier-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com/hasAnybodySeenHarry/helm-repository/production/'
    chart: notifier
    targetRevision: '*'
    helm:
      valueFiles:
      - values.yaml
      releaseName: prod-release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
