apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notifier
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com/hasAnybodySeenHarry/debt-tracker-services/production/'
    chart: notifier
    targetRevision: '*'
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: notifier-split
  namespace: default
spec:
  service: notifier
  backends:
  - service: notifier-v1
    weight: 500
  - service: notifier-v2
    weight: 500