apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: throttler
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com/hasAnybodySeenHarry/helm-repository/production/'
    chart: throttler
    targetRevision: '*'
    helm:
      valueFiles:
      - values.yaml
      # releaseName: prod-release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: throttler-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: throttler
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    interval: 15s