apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: throttler
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com/hasAnybodySeenHarry/debt-tracker-services/production/'
    chart: throttler
    targetRevision: '*'
    helm:
      valueFiles:
      - values.yaml
      # releaseName: prod-release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: throttler-split
  namespace: default
spec:
  service: throttler
  backends:
  - service: throttler-active
    weight: 500
  - service: throttler-preview
    weight: 500