{{- range .Values.apps }}
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: {{ . }}-metric-policy
  namespace: default
spec:
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: {{ . }}-metric-route
  requiredAuthenticationRefs:
  - name: {{ . }}-metric-authn
    kind: MeshTLSAuthentication
    group: policy.linkerd.io
{{- end }}
