{{- range .Values.apps }}
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: {{ . }}-probe-policy
  namespace: default
spec:
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: {{ . }}-probe-route
  requiredAuthenticationRefs:
  - name: {{ . }}-probe-authn
    kind: NetworkAuthentication
    group: policy.linkerd.io
---
{{- end }}