rules:
  custom:
    - seriesQuery: 'total_http_requests{service="throttler", namespace="default", job="throttler-active"}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "total_http_requests"
        as: "total_http_requests"
      metricsQuery: 'sum(rate(total_http_requests{service="throttler", namespace="default", job="throttler-active"}[1m])) by (pod)'

    - seriesQuery: 'rabbitmq_queue_messages_ready{service="rabbitmq-proxy", namespace="default"}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "rabbitmq_queue_messages_ready"
        as: "rabbitmq_queue_messages_ready"
      metricsQuery: "sum(rabbitmq_queue_messages_ready) by (pod)"
