apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
data:
  username: {{ "harry" | b64enc }}
  password: {{ "password" | b64enc }}
  host: {{ "rabbitmq-proxy" | b64enc }}
  port: {{ "5672" | toString | b64enc }}
