apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  name: {{ "expenses" | b64enc }}
  host: {{ "postgres-database" | b64enc }}
  username: {{ "harry" | b64enc }}
  password: {{ "password" | b64enc }}
  port: {{ "5432" | toString | b64enc }}
  maxOpenConn: {{ "30" | toString | b64enc }}
  maxIdleConn: {{ "30" | toString | b64enc }}