apiVersion: v1
kind: Pod
metadata:
  name: my-postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:alpine
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: password
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: name
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
