apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  username: {{ "harry" | b64enc }}
  password: {{ "password" | b64enc }}
  database: {{ "notifications" | b64enc }}
  host: {{ "mongo-database" | b64enc }}
  port: {{ "27017" | toString | b64enc }}