apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:alpine
    command: ["sh", "-c", "redis-server --requirepass $REDIS_PASSWORD"]
    ports:
    - containerPort: 6379
    env:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-secrets
          key: password
---
apiVersion: v1
kind: Service
metadata:
  name: redis-database
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
