prometheus:
  url: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
rules:
  custom:
  - seriesQuery: 'total_http_requests{service="throttler", namespace="default"}'
    resources:
      overrides:
        namespace:
          resource: namespace
    name:
      matches: ".*"
      as: "http_requests_total"
    metricsQuery: 'sum(rate(total_http_requests{service="throttler", namespace="default"}[1m]))'