prometheus:
  url: http://prometheus-kube-prometheus-prometheus.monitoring.svc
rules:
  custom:
  - seriesQuery: 'total_http_requests{service="throttler", namespace="default"}'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: "total_http_requests"
      as: "total_http_requests"
    metricsQuery: 'sum(rate(total_http_requests{service="throttler", namespace="default"}[1m])) by (pod)'